"""
Auditex -- Hash commitment scheme.
Implements the cryptographic commitment protocol used to prove reviewer independence.

Protocol (per D-06 in the spec):
  1. Reviewer computes its verdict independently.
  2. Reviewer computes: commitment = SHA256(verdict + nonce)
  3. Reviewer submits the commitment hash ONLY (verdict stays hidden).
  4. All commitments are collected.
  5. Reveal phase: each reviewer reveals (verdict, nonce).
  6. Coordinator verifies: SHA256(revealed_verdict + revealed_nonce) == committed_hash
  7. Any mismatch raises SecurityViolationError and is logged as a SECURITY_VIOLATION.

This is the technical proof of independent review -- any attempt to copy another
reviewer's verdict after seeing it would produce a commitment mismatch.

This module has NO external dependencies beyond stdlib hashlib and secrets.
"""
from __future__ import annotations

import hashlib
import secrets
import logging

logger = logging.getLogger(__name__)


class SecurityViolationError(Exception):
    """
    Raised when a hash commitment verification fails.
    Indicates that a reviewer's revealed verdict does not match its committed hash --
    a potential attempt to alter a verdict after seeing other reviewers' outputs.
    """


def generate_nonce() -> str:
    """
    Generate a cryptographically random 32-byte nonce as a hex string.

    Returns:
        64-character hex string (32 bytes of randomness).
    """
    return secrets.token_hex(32)


def compute_commitment(verdict: str, nonce: str) -> str:
    """
    Compute the SHA-256 commitment hash for a (verdict, nonce) pair.

    The commitment is: SHA256(verdict + nonce)
    where verdict and nonce are concatenated as UTF-8 strings before hashing.

    Args:
        verdict: The reviewer's verdict string (e.g. "APPROVE" or "REJECT").
        nonce:   The 64-character hex nonce generated by generate_nonce().

    Returns:
        64-character lowercase hex string of the SHA-256 digest.
    """
    combined = (verdict + nonce).encode("utf-8")
    digest = hashlib.sha256(combined).hexdigest()
    logger.debug(
        "compute_commitment: verdict=%s nonce=%s... -> %s...",
        verdict, nonce[:8], digest[:16],
    )
    return digest


def verify_commitment(verdict: str, nonce: str, committed_hash: str) -> bool:
    """
    Verify that SHA256(verdict + nonce) matches the previously committed hash.

    This is called during the reveal phase to confirm that a reviewer did not
    alter its verdict after seeing other reviewers' outputs.

    Args:
        verdict:        The revealed verdict (e.g. "APPROVE").
        nonce:          The revealed nonce.
        committed_hash: The hash submitted during the commitment phase.

    Returns:
        True if the commitment is valid.

    Raises:
        SecurityViolationError if the recomputed hash does not match committed_hash.
    """
    recomputed = compute_commitment(verdict, nonce)

    if recomputed != committed_hash:
        logger.error(
            "SECURITY_VIOLATION: commitment mismatch | "
            "verdict=%s nonce=%s... committed=%s... recomputed=%s...",
            verdict, nonce[:8], committed_hash[:16], recomputed[:16],
        )
        raise SecurityViolationError(
            f"Hash commitment verification failed. "
            f"Committed: {committed_hash[:16]}... "
            f"Recomputed: {recomputed[:16]}... "
            f"Verdict may have been altered after commitment."
        )

    logger.debug(
        "verify_commitment: PASSED | verdict=%s hash=%s...",
        verdict, committed_hash[:16],
    )
    return True
