version: '3.9'

services:

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - redis
      - postgres
    volumes:
      - ./backend:/app
    command: celery -A workers.celery_app worker --loglevel=info

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: auditex
      POSTGRES_PASSWORD: auditex_dev_pw
      POSTGRES_DB: auditex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auditex"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  foxmq:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./vertex-nodes/node-a/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  postgres_data:
  redis_data:
