"""
Auditex -- Report ORM model.
A Report is the human-readable Proof of Coordination (PoC) generated
from the Vertex event log after a task reaches COMPLETED status.
One Report per Task. Generated once, signed, never modified.
"""
import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base, TimestampMixin, UUIDPrimaryKeyMixin


class Report(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    PoC Report -- generated once per completed task.
    Contains plain-English narrative + structured EU AI Act export.
    Signed with the organisation's private key.
    """
    __tablename__ = "reports"

    task_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tasks.id"),
        nullable=False,
        unique=True,
        index=True,
    )

    # Plain-English narrative (generated by Claude from Vertex event log)
    narrative: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Structured exports
    eu_ai_act_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Full EU AI Act Article 9/13/17 structured export

    schema_version: Mapped[str] = mapped_column(
        String(50), nullable=False, default="eu_ai_act_v1"
    )

    # Cryptographic signature
    org_signature: Mapped[str | None] = mapped_column(Text, nullable=True)
    signed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    signing_key_id: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Vertex proof reference (the final event hash of the task's event chain)
    vertex_event_hash: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Generation metadata
    generated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    generator_model: Mapped[str | None] = mapped_column(String(100), nullable=True)
    # e.g. "claude-sonnet-4-6"

    # Export tracking
    export_count: Mapped[int] = mapped_column(
        nullable=False, default=0
    )
    last_exported_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships
    task = relationship("Task", back_populates="report")

    def __repr__(self) -> str:
        return f"<Report id={self.id} task={self.task_id} signed={self.signed_at is not None}>"
