from pathlib import Path
OUT = Path(r"C:/Users/v_sen/Documents/Projects/0001_Hack0014_Vertex_Swarm_Tashi/auditex/frontend/tests/demo/end-to-end-demo.spec.ts")
OUT.parent.mkdir(parents=True, exist_ok=True)
lines = []
def L(s): lines.append(s)
L('/**')
L(' * Auditex end-to-end captioned demo - submits real tasks through the real backend.')
L(' * For each test case: caption -> submit form -> watch pipeline run -> open result -> next.')
L(' * No mocking. Real Anthropic and OpenAI calls. Real Vertex consensus. Real timing.')
L(' *')
L(' * Run: cd frontend; npx playwright test tests/demo/end-to-end-demo.spec.ts --headed --project=chromium')
L(' * Out: frontend/test-results/.../video.webm (then copied to demo/)')
L(' */')
L("import { test, expect } from '@playwright/test'")
L("import { showCaption, hideCaption, showTitleCard, READ_SHORT } from './caption-overlay'")
L('')
L("const BASE = 'http://localhost:3000'")
L('')
L('interface DemoCase {')
L('  scene: string')
L('  title: string')
L('  given: string')
L('  when: string')
L('  then: string')
L('  expected: string')
L('  taskType: string  // e.g. ''contract_check''')
L('  document: string  // text to paste into the textarea')
L('  criteria: string[]  // labels to tick')
L('}')
L('')
L('const CASES: DemoCase[] = [')
L('  {')
L("    scene: 'TC-DEMO-1 of 3',")
L("    title: 'Contract Check - APPROVE path',")
L("    given: 'A clean Data Processing Agreement that fully covers Article 28 GDPR',")
L("    when: 'Compliance officer submits it for contract_check',")
L("    then: 'Pipeline runs Executor + 3 Reviewers, BFT consensus reaches APPROVE',")
L("    expected: 'Status COMPLETED with executor + reviewers + vertex hash visible',")
L("    taskType: 'contract_check',")
L("    criteria: ['Completeness'],")
L('    document: `Data Processing Agreement - TechCorp Ltd & Vendor Services Inc.')
L('')
L('1. Scope: Vendor processes personal data on behalf of TechCorp under this DPA.')
L('2. Purpose: Payment processing for e-commerce transactions (Art. 28 GDPR).')
L('3. Categories: Customer name, email, billing address, order history.')
L('4. Retention: 6 years post-transaction; deleted thereafter.')
L('5. Sub-processors: Annex A, with 30-day prior notification of changes.')
L('6. Security: AES-256 at rest, TLS 1.3 in transit, SOC 2 Type II certified.')
L('7. Data subject rights: access, rectification, erasure within 30 days.')
L('8. Breach notification: within 24 hours of any incident.')
L('9. International transfers: UK-EU Adequacy + SCCs.')
L('10. Audit rights: annual with 30-day notice.')
L('')
L('This DPA is complete and all Article 28 items are explicitly addressed.`,')
L('  },')
L('  {')
L("    scene: 'TC-DEMO-2 of 3',")
L("    title: 'Risk Analysis - REJECT path',")
L("    given: 'A high-risk loan application with impossible income claim',")
L("    when: 'Compliance officer submits it for risk_analysis',")
L("    then: 'Pipeline detects anomaly, all 3 reviewers vote REJECT',")
L("    expected: 'Status COMPLETED, recommendation REJECT, reasoning explains the red flag',")
L("    taskType: 'risk_analysis',")
L("    criteria: ['Income Verification', 'Risk Assessment'],")
L('    document: `Loan Application - Applicant ID 88472')
L('')
L('Stated annual income: GBP 4,500,000')
L('Stated employer: TechCorp Ltd (entry-level role, started 2 weeks ago)')
L('Loan amount requested: GBP 12,000,000 unsecured')
L('Term: 6 months bullet repayment')
L('Stated assets: cryptocurrency holdings (no exchange records provided)')
L('Stated purpose: investment in private offshore venture')
L('Provided documentation: 1 page CV, no payslips, no bank statements, no tax returns')
L('Credit history: no record found in standard UK credit reference agencies')
L('')
L('This application has multiple red flags consistent with money laundering or fraud.`,')
L('  },')
L('  {')
L("    scene: 'TC-DEMO-3 of 3',")
L("    title: 'Document Review - REQUEST_AMENDMENTS path',")
L("    given: 'An almost-complete employment verification missing one key field',")
L("    when: 'Compliance officer submits it for document_review',")
L("    then: 'Pipeline flags missing field, reviewers vote REQUEST_AMENDMENTS',")
L("    expected: 'Status COMPLETED, recommendation REQUEST_AMENDMENTS, specific gap noted',")
L("    taskType: 'document_review',")
L("    criteria: ['Employment Verification', 'Completeness'],")
L('    document: `Employment Verification - Subject: Jane Smith')
L('')
L('Employer: Northwind Logistics Ltd')
L('Position: Senior Operations Analyst')
L('Start date: 12 February 2024')
L('Employment type: Full-time, permanent')
L('Annual salary: ')
L('Hours: 40 per week')
L('Manager: Robert Chen (rchen@northwindlogistics.example)')
L('HR contact: Sarah Patel (hr@northwindlogistics.example)')
L('Letter dated and signed: 15 March 2026')
L('')
L('Note: salary field is blank above. The verifier must request this before approval.`,')
L('  },')
L(']')
L('')
L("test.describe('Auditex End-to-End Captioned Demo', () => {")
L("  test('Real submission walkthrough across 3 outcome paths', async ({ page }) => {")
L('    test.setTimeout(30 * 60 * 1000)  // 30 min budget; real LLM calls')
L('')
L('    await page.goto(BASE)')
L('    await page.waitForLoadState("networkidle", { timeout: 30000 }).catch(() => {})')
L('')
L("    await showTitleCard(page, 'Auditex', 'EU AI Act compliance audit pipeline. End-to-end demo: 3 real submissions, 3 outcome paths, no mocking. DoraHacks BUIDL #43345.', 4500)")
L('')
L('    for (let i = 0; i < CASES.length; i++) {')
L('      const c = CASES[i]')
L('')
L('      // Caption screen for this test case')
L('      await showCaption(page, {')
L('        scene: c.scene,')
L('        title: c.title,')
L('        given: c.given,')
L('        when: c.when,')
L('        then: c.then,')
L("        testData: ['Task type: ' + c.taskType, 'Criteria: ' + c.criteria.join(', ')],")
L('        expected: c.expected,')
L('        holdMs: 4500,')
L('      })')
L('      await hideCaption(page)')
L('')
L('      // Make sure dashboard is visible (not stuck on prev task detail)')
L("      const submitFormHeading = page.getByRole('heading', { name: /Submit New Task/i })")
L('      if (!(await submitFormHeading.isVisible().catch(() => false))) {')
L('        await page.goto(BASE)')
L('        await page.waitForTimeout(800)')
L('      }')
L('')
L('      // 1) Select task type')
L("      await page.locator('select').selectOption(c.taskType)")
L('      await page.waitForTimeout(400)')
L('')
L('      // 2) Type the document')
L("      const textarea = page.locator('textarea')")
L('      await textarea.click()')
L('      await textarea.fill(c.document)')
L('      await page.waitForTimeout(400)')
L('')
L('      // 3) Tick criteria checkboxes')
L('      for (const label of c.criteria) {')
L('        const cb = page.locator(`label:has-text("${label}") input[type="checkbox"]`)')
L('        if (!(await cb.isChecked().catch(() => false))) {')
L('          await cb.check({ force: true })')
L('          await page.waitForTimeout(250)')
L('        }')
L('      }')
L('      await page.waitForTimeout(400)')
L('')
L('      // 4) Click Submit Task')
L("      const submitBtn = page.getByRole('button', { name: /^Submit Task$/i })")
L('      await submitBtn.click()')
L('      await page.waitForTimeout(1500)  // give the new task time to appear in the list')
L('')
L('      // 5) Click into the just-submitted task (top of the list)')
L("      const firstTask = page.locator('button.w-full.text-left').first()")
L('      await firstTask.click()')
L('      await page.waitForTimeout(1000)')
L('')
L('      // 6) Wait for COMPLETED. Real LLM time. We do not artificially pace.')
L("      const detail = page.locator('[data-testid=\"task-detail\"]')")
L('      await expect(detail).toBeVisible({ timeout: 10000 })')
L('')
L('      // Wait for the COMPLETED status badge inside the task list (real polling, 3s cadence).')
L("      await expect(firstTask).toContainText(/COMPLETED/i, { timeout: 8 * 60 * 1000 })")
L('')
L('      // 7) Show the result: scroll through the detail panel slowly so viewers see the')
L('      // executor verdict, reviewer panel, vertex hash, compliance report.')
L('      for (let y = 0; y <= 1500; y += 200) {')
L("        await detail.evaluate((el, pos) => el.scrollTo({ top: pos, behavior: 'smooth' }), y)")
L('        await page.waitForTimeout(900)')
L('      }')
L('')
L('      // Pause 2s on the completed result so viewers see the final state')
L('      await page.waitForTimeout(2000)')
L('    }  // end for-each case')
L('')
L("    await showTitleCard(page, 'Auditex', 'github.com/vsenthil7/auditex   |   DoraHacks BUIDL #43345   |   See ENTERPRISE-GAP-REGISTER.md for honest current-state disclosure.', 4500)")
L('  })')
L('})')

OUT.write_text(chr(10).join(lines) + chr(10), encoding="utf-8")
print("wrote ", OUT.stat().st_size, "bytes")
